export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGIN_OUT = 'USER_LOGIN_OUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';

export const USER_UPDATE_PROFILES_REQUEST = 'USER_UPDATE_PROFILES_REQUEST';
export const USER_UPDATE_PROFILES_SUCCESS = 'USER_UPDATE_PROFILES_SUCCESS';
export const USER_UPDATE_PROFILES_FAIL = 'USER_UPDATE_PROFILES_FAIL';
export const USER_UPDATE_PROFILES_RESET = 'USER_UPDATE_PROFILES_RESET';
